# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-20 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200, unique=True)),
                ('rating', models.IntegerField()),
                ('slope', models.IntegerField()),
                ('par', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('strokes', models.IntegerField()),
                ('putts', models.IntegerField()),
                ('fairways_hit', models.IntegerField()),
                ('gir', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rounds.Course')),
            ],
        ),
    ]
