# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-20 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rounds.Course', to_field='course'),
        ),
    ]
