# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_auto_20170219_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drdist', models.IntegerField()),
                ('dracc', models.IntegerField()),
                ('par3tee', models.IntegerField()),
                ('lngdist', models.IntegerField()),
                ('lngacc', models.IntegerField()),
                ('shtdist', models.IntegerField()),
                ('shtacc', models.IntegerField()),
                ('pitch', models.IntegerField()),
                ('chip', models.IntegerField()),
                ('putt', models.IntegerField()),
                ('penal', models.IntegerField()),
                ('coursemgmt', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='round',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AddField(
            model_name='shots',
            name='date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rounds.Round', to_field='date'),
        ),
    ]
