# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0003_auto_20170304_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
