# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0004_auto_20170305_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='equistroks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
